# Generated by Django 6.0.8 on 2026-09-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmail_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmailmailbox",
            name="encrypted_refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="gmailmailbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("connected", "Connected"),
                    ("syncing", "Syncing"),
                    ("error", "Error"),
                    ("needs_reconnect", "Needs reconnect"),
                ],
                default="connected",
                max_length=16,
            ),
        ),
    ]
